plugins:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-thread_safety

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  UseProjectIndex: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
