# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "irb"
gem "rake-compiler", "~> 1.2", require: false
gem "rspec", "~> 3.13", require: false
gem "rubocop", "~> 1.65", require: false
gem "rubocop-performance", require: false
gem "rubocop-rspec", "~> 3.0", require: false
gem "rubocop-thread_safety", require: false
gem "rubydex", require: false
