# frozen_string_literal: true

require "bundler/gem_tasks"
require "rake/extensiontask"
require "rspec/core/rake_task"
require "rubocop/rake_task"

task default: %i[compile spec rubocop]

Rake::ExtensionTask.new("pdf_inspector_native") do |c|
  c.lib_dir = "lib/pdf_inspector"
end

RSpec::Core::RakeTask.new(:spec)

RuboCop::RakeTask.new
