#!/usr/bin/env python3
"""Regenerate the C# lookup tables from the Rust reference sources.

The tables are mechanical transliterations of `reference/src/glyph_names.rs`
and `reference/src/adobe_korea1.rs`. Both are generated files upstream, so
regenerating rather than hand-editing keeps them in step.

Usage: python3 scripts/gen_tables.py
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REFERENCE = ROOT / "reference" / "src"
OUT_TEXT = ROOT / "src" / "PdfInspector" / "Text"
OUT_TOUNICODE = ROOT / "src" / "PdfInspector" / "ToUnicode"


def rust_char_to_codepoint(literal: str) -> int:
    """Decode a Rust `char` literal (already stripped of its quotes)."""
    if literal.startswith("\\u{"):
        return int(literal[3:-1], 16)
    if literal.startswith("\\x"):
        return int(literal[2:4], 16)
    if literal == "\\\\":
        return 0x5C
    if literal == "\\'":
        return 0x27
    if literal == '\\"':
        return 0x22
    if literal == "\\n":
        return 0x0A
    if literal == "\\r":
        return 0x0D
    if literal == "\\t":
        return 0x09
    if literal == "\\0":
        return 0x00
    assert len(literal) == 1, f"unexpected char literal: {literal!r}"
    return ord(literal)


def csharp_char(codepoint: int) -> str:
    """Render a codepoint as a C# char literal, escaping anything non-printable."""
    if codepoint == 0x27:
        return "'\\''"
    if codepoint == 0x5C:
        return "'\\\\'"
    if 0x20 <= codepoint < 0x7F:
        return f"'{chr(codepoint)}'"
    return f"'\\u{codepoint:04X}'"


def csharp_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def gen_glyph_names() -> None:
    source = (REFERENCE / "glyph_names.rs").read_text(encoding="utf-8")

    entries: list[tuple[str, int]] = []
    seen: set[str] = set()
    for name, literal in re.findall(r'm\.insert\("((?:[^"\\]|\\.)*)", \'(.*?)\'\);', source):
        decoded_name = name.replace('\\"', '"').replace("\\\\", "\\")
        if decoded_name in seen:
            # Later inserts (the PUA overrides) win, matching Rust HashMap semantics.
            entries = [e for e in entries if e[0] != decoded_name]
        seen.add(decoded_name)
        entries.append((decoded_name, rust_char_to_codepoint(literal)))

    lines = [
        "// Generated by scripts/gen_tables.py from reference/src/glyph_names.rs — do not edit by hand.",
        "",
        "namespace PdfInspector.Text;",
        "",
        "internal static partial class GlyphNames",
        "{",
        f"    /// <summary>Adobe Glyph List and related names, plus the PUA overrides the reference build applies ({len(entries)} entries).</summary>",
        "    private static readonly Dictionary<string, char> Table = new(StringComparer.Ordinal)",
        "    {",
    ]
    for name, codepoint in entries:
        lines.append(f"        [{csharp_string(name)}] = {csharp_char(codepoint)},")
    lines += ["    };", "}", ""]

    OUT_TEXT.mkdir(parents=True, exist_ok=True)
    (OUT_TEXT / "GlyphNames.Table.cs").write_text("\n".join(lines), encoding="utf-8")
    print(f"GlyphNames.Table.cs: {len(entries)} entries")


def gen_korea1() -> None:
    source = (REFERENCE / "adobe_korea1.rs").read_text(encoding="utf-8")
    pairs = re.findall(r"\((\d+), 0x([0-9A-Fa-f]+)\),", source)

    lines = [
        "// Generated by scripts/gen_tables.py from reference/src/adobe_korea1.rs — do not edit by hand.",
        "",
        "namespace PdfInspector.ToUnicode;",
        "",
        "/// <summary>",
        "/// Adobe-Korea1 CID→Unicode mapping, generated upstream from the",
        "/// adobe-type-tools/cmap-resources Adobe-Korea1-2 cid2code.txt UniKS-UCS2 column.",
        "/// </summary>",
        "internal static class AdobeKorea1",
        "{",
        f"    /// <summary>CIDs, ascending, paired index-for-index with <see cref=\"Values\"/> ({len(pairs)} entries).</summary>",
        "    private static readonly ushort[] Cids =",
        "    [",
    ]

    def chunk(values: list[str], per_line: int = 12) -> list[str]:
        out = []
        for i in range(0, len(values), per_line):
            out.append("        " + " ".join(v + "," for v in values[i : i + per_line]))
        return out

    lines += chunk([cid for cid, _ in pairs])
    lines += ["    ];", "", "    private static readonly ushort[] Values =", "    ["]
    lines += chunk([f"0x{value.upper()}" for _, value in pairs])
    lines += [
        "    ];",
        "",
        "    /// <summary>Looks up a CID, returning null when the table has no mapping for it.</summary>",
        "    public static char? Lookup(ushort cid)",
        "    {",
        "        var index = Array.BinarySearch(Cids, cid);",
        "        return index < 0 ? null : (char)Values[index];",
        "    }",
        "",
        "    /// <summary>Every CID→character pair in the table, in ascending CID order.</summary>",
        "    public static IEnumerable<(ushort Cid, char Char)> Entries()",
        "    {",
        "        for (var i = 0; i < Cids.Length; i++)",
        "        {",
        "            yield return (Cids[i], (char)Values[i]);",
        "        }",
        "    }",
        "}",
        "",
    ]

    OUT_TOUNICODE.mkdir(parents=True, exist_ok=True)
    (OUT_TOUNICODE / "AdobeKorea1.cs").write_text("\n".join(lines), encoding="utf-8")
    print(f"AdobeKorea1.cs: {len(pairs)} entries")


if __name__ == "__main__":
    gen_glyph_names()
    gen_korea1()
